# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle_customerA
    environment:
      ORACLE_PASSWORD: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
  postgres_data:
  oracle_data:
